

Lot.create!([
       { brand_id:1, number: "501"},
       { brand_id:1, number: "502"},
       { brand_id:1, number: "505"},
       { brand_id:1, number: "510"},
       { brand_id:1, number: "511"},
       { brand_id:1, number: "512"},
       { brand_id:1, number: "514"},
       { brand_id:1, number: "517"},
       { brand_id:1, number: "519"},
       { brand_id:1, number: "541"},
       { brand_id:1, number: "550"},
       { brand_id:1, number: "606"},
       { brand_id:2, number: "501xx"},
       { brand_id:3, number: "101-Z"},
       { brand_id:3, number: "101-J"},
       { brand_id:3, number: "102"},
       { brand_id:4, number: "Petit Standerd"},
       { brand_id:4, number: "Petit New Standerd"},
       { brand_id:4, number: "New Standerd"},
       { brand_id:5, number: "11MW"},
       { brand_id:5, number: "11MWZ"},
       { brand_id:5, number: "77MWZ"},
       ])
